# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Operational PyPI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install package from pypi
      run: |
        python -m pip install pysigfig
    - name: Test Normal Operations
      run: |
        python -c "import math; import pysigfig as pysf; x = pysf.Float('1.23'); y = pysf.Float('4.5'); print(x + y); print(x * y); print(x - y); print(x / y)"
